name: pl_env
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - pip=22.3.1
  - python=3.10.8
  - pip:
      - lightning-utilities==0.5.0
      - mypy==0.991
      - numpy==1.24.1
      - pytorch-lightning==1.8.6
      - tensorboard==2.11.0
